services:
  mysql:
    #image: mysql:latest # for mac intel, windows
    image: arm64v8/mysql:9.0.1 # for Mac Apple Silicon(M1, M2, ...)
    container_name: mysql_container
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "" #blank password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "shop_app_online"
    restart: always
    networks:
      - shop_app_online
  
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64  
    container_name: phpmyadmin-container
    restart: always
    depends_on: 
      - mysql
    ports: 
      - "90:80" #port mapping 
    environment: 
      PMA_HOST: mysql #phpMyAdmin in Host, PMA = PHP My Admin
      PMA_PORT: 3306
      UPLOAD_LIMIT: 500M 
    networks: 
      - shop_app_online

networks:
  shop_app_online: 
    name: shop_app_online
    driver: bridge

#docker-compose -f ./deployments.yml up -d phpmyadmin
#docker-compose -f ./deployments.yml up -d 
#docker-compose -f ./deployments.yml down
